export type NumberTheoryProps = { n: number };
export type TwoNumberTheoryProps = { a: number; b: number };

export type FactorialProps = NumberTheoryProps;
export type FibonacciProps = NumberTheoryProps;
export type IsPrimeProps = NumberTheoryProps;
export type IsCompositeProps = NumberTheoryProps;
export type GcdProps = TwoNumberTheoryProps;
export type LcmProps = TwoNumberTheoryProps;
export type PrimeFactorsProps = NumberTheoryProps;
export type BinomialProps = { n: number; k: number };
export type HermiteProps = { n: number; x: number };
export type LaguerreProps = { n: number; x: number };
export type LegendreProps = { n: number; x: number };
export type ChebyshevProps = { n: number; x: number };
export type BesselProps = { n: number; x: number };
export type GammaProps = NumberTheoryProps;
export type BetaProps = { x: number; y: number };
export type ZetaProps = NumberTheoryProps;
