export type NumberTheoryFunction = { n: number };
export type TwoNumberTheoryFunction = { a: number; b: number };

export type FactorialFunction = NumberTheoryFunction;
export type FibonacciFunction = NumberTheoryFunction;
export type IsPrimeFunction = NumberTheoryFunction;
export type IsCompositeFunction = NumberTheoryFunction;
export type GcdFunction = TwoNumberTheoryFunction;
export type LcmFunction = TwoNumberTheoryFunction;
export type PrimeFactorsFunction = NumberTheoryFunction;
export type BinomialFunction = { n: number; k: number };
export type HermiteFunction = { n: number; x: number };
export type LaguerreFunction = { n: number; x: number };
export type LegendreFunction = { n: number; x: number };
export type ChebyshevFunction = { n: number; x: number };
export type BesselFunction = { n: number; x: number };
export type GammaFunction = NumberTheoryFunction;
export type BetaFunction = { x: number; y: number };
export type ZetaFunction = NumberTheoryFunction;
